// <auto-generated />
using System;
using ConectaPorto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace ConectaPorto.Api.Migrations
{
    [DbContext(typeof(ConectaPortoDbContext))]
    [Migration("20240509150847_primeira")]
    partial class primeira
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConectaPorto.Dto.CarrierDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CarrierModeId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DataChegada")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("PODId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("POLId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("VisitStateId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CarrierModeId");

                    b.HasIndex("PODId");

                    b.HasIndex("POLId");

                    b.HasIndex("VisitStateId");

                    b.ToTable("Carrier");
                });

            modelBuilder.Entity("ConectaPorto.Dto.CarrierModeDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Veiculo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("CarrierMode");
                });

            modelBuilder.Entity("ConectaPorto.Dto.ClienteDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ConectaPorto.Dto.FreightKindDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cicla")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("FreightKind");
                });

            modelBuilder.Entity("ConectaPorto.Dto.IsoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("ISO");
                });

            modelBuilder.Entity("ConectaPorto.Dto.PortoDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cicla")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Portos");
                });

            modelBuilder.Entity("ConectaPorto.Dto.TransitStateDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TransitState");
                });

            modelBuilder.Entity("ConectaPorto.Dto.TransportadoraDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cicla")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Transportadoras");
                });

            modelBuilder.Entity("ConectaPorto.Dto.UnitCategoryDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("UnitCategory");
                });

            modelBuilder.Entity("ConectaPorto.Dto.UnitDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Booking")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("CarrierIbId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CarrierObId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("FreightKindId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IsoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nbr")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("ProprietarioId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TransitStateId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TransportadoraId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("CarrierIbId");

                    b.HasIndex("CarrierObId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FreightKindId");

                    b.HasIndex("IsoId");

                    b.HasIndex("ProprietarioId");

                    b.HasIndex("TransitStateId");

                    b.HasIndex("TransportadoraId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("ConectaPorto.Dto.UsuarioDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ConectaPorto.Dto.VisitStateDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Situacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("VisitState");
                });

            modelBuilder.Entity("ConectaPorto.Dto.CarrierDto", b =>
                {
                    b.HasOne("ConectaPorto.Dto.CarrierModeDto", "CarrierMode")
                        .WithMany()
                        .HasForeignKey("CarrierModeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaPorto.Dto.PortoDto", "POD")
                        .WithMany()
                        .HasForeignKey("PODId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaPorto.Dto.PortoDto", "POL")
                        .WithMany()
                        .HasForeignKey("POLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaPorto.Dto.VisitStateDto", "VisitState")
                        .WithMany()
                        .HasForeignKey("VisitStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarrierMode");

                    b.Navigation("POD");

                    b.Navigation("POL");

                    b.Navigation("VisitState");
                });

            modelBuilder.Entity("ConectaPorto.Dto.UnitDto", b =>
                {
                    b.HasOne("ConectaPorto.Dto.CarrierDto", "CarrierIb")
                        .WithMany()
                        .HasForeignKey("CarrierIbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaPorto.Dto.CarrierDto", "CarrierOb")
                        .WithMany()
                        .HasForeignKey("CarrierObId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaPorto.Dto.UnitCategoryDto", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaPorto.Dto.FreightKindDto", "FreightKind")
                        .WithMany()
                        .HasForeignKey("FreightKindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaPorto.Dto.IsoDto", "Iso")
                        .WithMany()
                        .HasForeignKey("IsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaPorto.Dto.ClienteDto", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaPorto.Dto.TransportadoraDto", "TransitState")
                        .WithMany()
                        .HasForeignKey("TransitStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConectaPorto.Dto.TransportadoraDto", "Transportadora")
                        .WithMany()
                        .HasForeignKey("TransportadoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CarrierIb");

                    b.Navigation("CarrierOb");

                    b.Navigation("Categoria");

                    b.Navigation("FreightKind");

                    b.Navigation("Iso");

                    b.Navigation("Proprietario");

                    b.Navigation("TransitState");

                    b.Navigation("Transportadora");
                });
#pragma warning restore 612, 618
        }
    }
}
