CREATE TABLE UNIT (
	ID NUMBER PRIMARY KEY,
	NBR VARCHAR(11) UNIQUE,
	ISO VARCHAR(4)
	SHIPPER VARCHAR(40),
	CATEGORIA VARCHAR(10),
	TRANSPORTADORA VARCHAR(3),
	BOOKING VARCHAR(11),
	FREIGHT_KIND VARCHAR(3),
	TRANSIT_STATE VARCHAR(10),
	CARRIER_IB VARCHAR(10),
	CARRIER_OB VARCHAR(10),
	USUARIO_CRIACAO NUMBER,
	USUARIO_ALTERACAO NUMBER
);

CREATE TABLE CARRIER (
	ID NUMBER PRIMARY KEY,
	NBR VARCHAR(10) UNIQUE,
	VISIT_STATE VARCHAR(10),
	DATA_PARTUDA TIMESTAMP,
	DATA_CHEGADA TIMESTAMP,
	POL VARCHAR(3),
	POD VARCHAR(3),
	CARRIER_MODE VARCHAR(10),
	USUARIO_CRIACAO NUMBER,
	USUARIO_ALTERACAO NUMBER
);

