CREATE TABLE ISO(
	ID NUMBER PRIMARY KEY,
	CODE VARCHAR(4) UNIQUE,
	DESCRIPT VARCHAR(10),
	USUARIO_CRIACAO NUMBER,
	USUARIO_ALTERACAO NUMBER
);

CREATE TABLE CLIENTE(
	ID NUMBER PRIMARY KEY,
	NOME VARCHAR(40),
	USUARIO_CRIACAO NUMBER,
	USUARIO_ALTERACAO NUMBER
);

CREATE TABLE UNIT_CATEGORY(
	ID NUMBER PRIMARY KEY,
	CATEGORY VARCHAR(10) UNIQUE,
	USUARIO_CRIACAO NUMBER,
	USUARIO_ALTERACAO NUMBER
);

CREATE TABLE TRANSIT_STATE(
	ID NUMBER PRIMARY KEY,
	STATE VARCHAR(10) UNIQUE,
	USUARIO_CRIACAO NUMBER,
	USUARIO_ALTERACAO NUMBER
);

CREATE TABLE VISIT_STATE(
	ID NUMBER PRIMARY KEY,
	STATE VARCHAR(10) UNIQUE,
	USUARIO_CRIACAO NUMBER,
	USUARIO_ALTERACAO NUMBER
);

CREATE TABLE CARRIER_MODE(
	ID NUMBER PRIMARY KEY,
	VEICULO VARCHAR(10) UNIQUE,
	USUARIO_CRIACAO NUMBER,
	USUARIO_ALTERACAO NUMBER
);

CREATE TABLE TRANSPORTADORA(
	ID NUMBER PRIMARY KEY,
	CICLA VARCHAR(3) UNIQUE,
	NOME VARCHAR(40),
	USUARIO_CRIACAO NUMBER,
	USUARIO_ALTERACAO NUMBER
);

CREATE TABLE PORTO(
	ID NUMBER PRIMARY KEY,
	CICLA VARCHAR(3) UNIQUE,
	CIDADE VARCHAR(20) UNIQUE,
	PAIS VARCHAR(20),
	USUARIO_CRIACAO NUMBER,
	USUARIO_ALTERACAO NUMBER
);

CREATE TABLE FREIGHT_KIND(
	ID NUMBER PRIMARY KEY,
	CICLA VARCHAR(3) UNIQUE,
	DESCRIPT VARCHAR(20),
	USUARIO_CRIACAO NUMBER,
	USUARIO_ALTERACAO NUMBER
);